# Generated by qwen2.5-coder (Iter 10) on 2025-12-12 14:00:00
import numpy as np

import numpy as np

# reward_shaping.py

def calculate_reward(observation, original_reward, terminated, truncated, info):
    """
    Args:
        observation (np.array): State vector (LunarLander has 8 values).
        original_reward (float): Reward from the env.
        terminated (bool): Crash or Landed.
        truncated (bool): Timeout.
        info (dict): Diagnostic info.
    """
    
    # Extract state variables
    x_position, y_position, x_velocity, y_velocity, angle, angular_velocity, left_leg_contact, right_leg_contact = observation
    
    # Constants
    X_PENALTY_WEIGHT = 10.0  # Increased penalty for large X-Positions
    VERTICAL_VELOCITY_BONUS = 5.0
    SIDE_ENGINE_PENALTY = 0.5  # Reduced penalty for high usage of side engines
    MAIN_ENGINE_BONUS = 12.0  # Enhanced bonus for using the main engine effectively
    BALANCE_REWARD = 0.3
    
    # Penalize large X-Positions
    x_penalty = abs(x_position) * X_PENALTY_WEIGHT
    
    # Reward lower vertical velocity when near the ground and Main Engine is active
    main_engine_active = info.get('main_engine_used', False)
    if y_position < 0.5:
        vertical_velocity_bonus = abs(y_velocity) * VERTICAL_VELOCITY_BONUS * main_engine_active
    else:
        vertical_velocity_bonus = 0
    
    # Penalize excessive Side Engine usage
    side_engine_used = info.get('side_engine_used', 0)
    side_engine_penalty = side_engine_used ** 2 * SIDE_ENGINE_PENALTY  # Quadratic penalty for high usage of side engines
    
    # Encourage balanced engine use
    balance_reward = BALANCE_REWARD * (1 - abs(x_velocity) / np.abs(np.max(observation[:2])))
    
    # Bonus for using the main engine aggressively near the ground
    if y_position < 0.5 and main_engine_active:
        main_engine_bonus = MAIN_ENGINE_BONUS * (1 + x_velocity / np.abs(np.max(observation[:2]))) ** 2  # Quadratic bonus for using the main engine effectively
    else:
        main_engine_bonus = 0
    
    # Combine all rewards
    shaped_reward = original_reward - x_penalty + vertical_velocity_bonus - side_engine_penalty + balance_reward + main_engine_bonus

    return shaped_reward