# Generated by dolphincoder:7b (Iter 1) on 2025-12-20 09:09:34
import numpy as np


def calculate_reward(observation, original_reward, terminated, truncated, info):
    """
    Args:
        observation  (np.array): State vector (LunarLander has 8 values).
        original_reward   (float): Reward from the env.
        terminated   (bool): Crash or Landed.
        truncated   (bool): Timeout.
        info   (dict): Diagnostic info.
    """

    # Calculate shaped reward based on improvement plan
    shaped_reward = original_reward + 20 if not terminated and not truncated else original_reward - abs(observation[3]) * 10 + np.abs((observation[4] - observation[5])/0.6) * 5 - info["entropy"]

    return shaped_reward